# Generated by Django 4.1.1 on 2022-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('data1', models.CharField(blank=True, db_column='Data1', max_length=255, null=True)),
                ('data2', models.CharField(blank=True, db_column='Data2', max_length=255, null=True)),
                ('data3', models.CharField(blank=True, db_column='Data3', max_length=255, null=True)),
                ('data4', models.CharField(blank=True, db_column='Data4', max_length=255, null=True)),
            ],
            options={
                'db_table': 'table1',
                'managed': False,
            },
        ),
    ]
